name: Pull Request Tests
on: pull_request

jobs:
  diff-check:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.diff-check.outputs.output }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Checking if sparsezoo was changed"
        id: diff-check
        run: >
          (git diff --name-only origin/main HEAD | grep -E "[src|tests]/sparsezoo|setup.py")
          && echo "::set-output name=output::1" || echo "::set-output name=output::0"
  tests:
    runs-on: ubuntu-latest
    needs: diff-check
    if: ${{needs.diff-check.outputs.diff == 1}}
    steps:
      - uses: actions/checkout@v2
      - name: "âš™ï¸ Install dependencies"
        run: pip3 install .[dev]
      - name: "ğŸ”¬ Running tests"
        run: make test
